config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :posts, except: [:update, :edit, :new, :show] do
    member do
      get 'image'
      get 'download'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/concerns/image_processing.rb
require 'mini_magick'

module ImageProcessing
  extend ActiveSupport::Concern

  GRAVITY = 'center'.freeze
  TEXT_POSITION = '0,0'.freeze
  FONT = './app/assets/fonts/OpenSans-SemiboldItalic.ttf'.freeze
  FONT_SIZE = 72.freeze
  INDENTION_COUNT = 11.freeze
  FONT_COLOR = '#FFFFFF'.freeze
  STOROKE_COLOR = '#000000'.freeze
  STOROKE_WITDH = 1.freeze

  TXT_LGTM = 'LGTM'.freeze

  def build(image)
    @image = MiniMagick::Image.open(image)
    configuration(TXT_LGTM)
  end

  private

  def configuration(text)
    @image.combine_options do |config|
      config.font FONT
      config.fill FONT_COLOR
      config.gravity GRAVITY
      config.pointsize FONT_SIZE
      config.draw "text #{TEXT_POSITION} '#{text}'"
      config.stroke STOROKE_COLOR
      config.strokewidth STOROKE_WITDH
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ImageProcessing

  def index
    @q= current_user.posts.ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(12).order(id: :desc)
  end

  def create
    processed_image = build(permit_params[:image].path)
    File.open(processed_image.path) do |file|
      @image_binary = file.read
    end
    @post = current_user.posts.new(
      name: permit_params[:name],
      image: @image_binary,
      filetype: permit_params[:image].content_type,
    )
    @post.save!
    redirect_to posts_path
  end

  def image
    @post = Post.find(params[:id])
    send_data @post.image, type: @post.filetype
  end

  def download
    @post = Post.find(params[:id])
    send_data @post.image, type: @post.filetype, disposition: 'attachment'
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "image deleted"
    redirect_to posts_path
  end

  private

  def permit_params
    params.require(:post).permit(:name, :image)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_user_modal.haml
%button.btn.btn-primary{"data-target" => "#modal1", "data-toggle" => "modal", :type => "button"}
  Launch demo modal

#modal1.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "label1", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#label1.modal-title Modal title
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        Modal body
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button"} OK

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LGTMCreator
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = analytics_init if Rails.env.production?
  %body
    .navbar.navbar-dark.bg-dark.box-shadow
      .container.d-flex.justify-content-between
        %a.navbar-brand.d-flex.align-items-center{href: root_path}
          %strong LGTMCreator
        - if user_signed_in?
          = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'text-white'
    = yield

  %footer.footer-copyright.text-center.py-3
    © 2019 Copyright NISHIO-K

app/views/posts/index.haml
.album.py-3.bg-light
  .container
    = search_form_for(@q, url: posts_path) do |f|
      = f.search_field :name_cont, class: 'form-control', placeholder: 'Search'
  .container.py-2
    .row
      .col-md-4
        .card.mb-4.box-shadow
          = form_for Post.new do |f|
            %img#img_prev.hidden{:src => "#", :style => "height: 225px; width: 100%; display: block; display:none;"}
            #img_default{:style => "height: 225px; width: 100%; display: block;"}
              %label#select_file
                Select Image
                = f.file_field :image
            .card-body
              .row
                .col-sm-9
                  = f.text_field :name, placeholder: 'Title'
                .col-sm-3
                  = f.submit "Send", class: 'btn btn-sm btn-outline-secondary'   

      - @posts.each do |post|
        .col-md-4
          .card.mb-4.box-shadow
            %img.card-img-top{:alt => "image", "data-holder-rendered" => "true", :src => image_post_path(post.id), :style => "height: 225px; width: 100%; display: block;"}/
            .card-body
              .d-flex.justify-content-between.align-items-center
                .btn-group
                  = link_to "DL", download_post_path(post.id), class: 'btn btn-sm btn-outline-secondary'
                  = link_to "destroy", post_path(post.id), method: :delete , data: {confirm: "OK?"}, class: 'btn btn-sm btn-outline-secondary'
                %small.text-muted= post.name
    .mx-auto
      = paginate @posts

:javascript
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
 
      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
        $('#img_prev').toggle();
        $('#img_default').toggle();
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#post_image").change(function() {
    readURL(this);
  });